### ISSUE TITLE
Challenge 2, Task 2: Use the "Get Data" UI (User Interface) wizard to ingest data from Azure blob storage - work around 

### ISSUE THREAD

**Issue by Mvenkateswaramma** [microsoft/FabricRTA-in-a-Day#23]
Hello,  in the Challenge 2, Task 2: Use the "Get Data" UI (User Interface) wizard to ingest data from Azure blob storage - work around:  Link to Source URL:**https://logsbenchmark00.blob.core.windows.net/logsbenchmark-onegb/2014/?sp=rl&st=2022-08-18T00:00:00Z&se=2030-01-01T00:00:00Z&spr=https&sv=2021-06-08&sr=c&sig=5pjOow5An3%2BTs5mZ%2FyosJBPtDvV7%2FXfDO8pLEeeylVc%3**  is not working please find the screenshot and do needful thanks
![RTA-URI Issue](https://github.com/microsoft/FabricRTA-in-a-Day/assets/106800146/59bcdd60-ce58-41fc-bdf3-027adf4cc6fa)

**Comment by hfleitas** [comment]
Pls use the BackupURL paths instead. See here: https://github.com/microsoft/FabricRTA-in-a-Day/blob/main/assets/blobURIbackup.md

**Comment by hfleitas** [comment]
Lab1 markdown updated.

**Comment by tfadmin87a** [comment]
Hello Hiram Fleitas, I have used the BackupURL paths as suggested, but I am still encountering the same issue.Please help me 

<img width="734" alt="Image" src="https://github.com/user-attachments/assets/f5011eef-4a31-40fb-ba86-208b52c717dc" />
